title: Cellular Biophysics & Modeling
description: neuroscience and dynamics @ William & Mary
url: ""
baseurl: ""
brand_mark: CBM
original_site: ""
exported: ""

markdown: kramdown
future: true
permalink: /posts/:slug/

collections:
  materials:
    output: true
    permalink: /pages/:name/

defaults:
  - scope:
      path: ""
      type: materials
    values:
      layout: page
      kind: page
  - scope:
      path: ""
      type: posts
    values:
      layout: page
      kind: post

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - README.md
